from decimal import Decimal, InvalidOperation
from typing import Any

from django.contrib import messages
from django.shortcuts import redirect
from django.views.generic import TemplateView

from core.forms import PriceChangeRequestForm
from services.api_client import ApiClientError, api_get, api_post


def build_product_lookup() -> dict[int, dict[str, Any]]:
    try:
        products = api_get("/products")
    except ApiClientError:
        return {}

    return {
        product["id"]: product
        for product in products
        if product.get("id") is not None
    }


def get_product_display(
    product_id: int | None,
    product_lookup: dict[int, dict[str, Any]],
) -> dict[str, Any]:
    if product_id is None:
        return {
            "product_code": "N/A",
            "product_name": "N/A",
            "image_url": None,
            "image_alt": "Product image",
        }

    product = product_lookup.get(product_id)

    if not product:
        return {
            "product_code": f"#{product_id}",
            "product_name": f"Product #{product_id}",
            "image_url": None,
            "image_alt": "Product image",
        }

    return {
        "product_code": product.get("code") or f"#{product_id}",
        "product_name": product.get("name") or f"Product #{product_id}",
        "image_url": product.get("image_url"),
        "image_alt": product.get("image_alt") or product.get("name") or "Product image",
    }


class HomeView(TemplateView):
    template_name = "core/home.html"


class DashboardView(TemplateView):
    template_name = "core/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["api_error"] = None
        context["kpi_cards"] = []

        try:
            kpis = api_get("/kpis")
        except ApiClientError as exc:
            context["api_error"] = str(exc)
            return context

        context["kpi_cards"] = [
            {
                "label": "Total sales",
                "value": self.format_number(kpis.get("total_sales_count")),
                "description": "Number of sales transactions.",
            },
            {
                "label": "Total quantity sold",
                "value": self.format_number(kpis.get("total_quantity")),
                "description": "Total units sold across all transactions.",
            },
            {
                "label": "Total revenue",
                "value": self.format_number(kpis.get("total_revenue")),
                "description": "Revenue generated by all sales.",
            },
            {
                "label": "Promo sales",
                "value": self.format_number(kpis.get("promo_sales_count")),
                "description": "Sales transactions linked to a promotion.",
            },
            {
                "label": "Promo revenue",
                "value": self.format_number(kpis.get("promo_revenue")),
                "description": "Revenue generated by promotional sales.",
            },
            {
                "label": "Promo sales share",
                "value": self.format_percentage(kpis.get("promo_sales_share")),
                "description": "Share of sales transactions linked to promotions.",
            },
            {
                "label": "Average order value",
                "value": self.format_number(kpis.get("average_order_value")),
                "description": "Average revenue per sales transaction.",
            },
        ]

        return context

    @staticmethod
    def format_number(value):
        if value is None:
            return "N/A"

        try:
            return f"{Decimal(str(value)):,.2f}"
        except (InvalidOperation, ValueError):
            return str(value)

    @staticmethod
    def format_percentage(value):
        if value is None:
            return "N/A"

        try:
            return f"{Decimal(str(value)) * Decimal('100'):.2f}%"
        except (InvalidOperation, ValueError):
            return str(value)


class ProductsView(TemplateView):
    template_name = "core/products.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["api_error"] = None
        context["products"] = []

        try:
            products = api_get("/products")
        except ApiClientError as exc:
            context["api_error"] = str(exc)
            return context

        context["products"] = [
            {
                "code": product.get("code") or "N/A",
                "name": product.get("name") or "N/A",
                "brand": product.get("brand") or "N/A",
                "model": product.get("model") or "N/A",
                "family_name": self.get_family_name(product),
                "description": product.get("description") or "N/A",
                "status": "Active" if product.get("active") is True else "Inactive",
                "image_url": product.get("image_url"),
                "image_alt": product.get("image_alt") or product.get("name") or "Product image",
            }
            for product in products
        ]

        return context

    @staticmethod
    def get_family_name(product):
        family = product.get("family")

        if not family:
            return "N/A"

        return family.get("name") or "N/A"


class PricesView(TemplateView):
    template_name = "core/prices.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["api_error"] = None
        context["prices"] = []

        try:
            prices = api_get("/prices")
        except ApiClientError as exc:
            context["api_error"] = str(exc)
            return context

        product_lookup = build_product_lookup()

        for price in prices:
            product_display = get_product_display(
                price.get("product_id"),
                product_lookup,
            )

            context["prices"].append(
                {
                    "product_code": price.get("product_code") or product_display["product_code"],
                    "product_name": price.get("product_name") or product_display["product_name"],
                    "image_url": product_display["image_url"],
                    "image_alt": product_display["image_alt"],
                    "scope": price.get("price_scope") or "N/A",
                    "scope_label": self.get_scope_label(price.get("price_scope")),
                    "type": price.get("price_type") or "N/A",
                    "amount": self.format_amount(
                        price.get("amount"),
                        price.get("currency_code"),
                    ),
                    "country_id": price.get("country_id") or "N/A",
                    "store_id": price.get("store_id") or "N/A",
                    "effective_from": price.get("effective_from") or "N/A",
                    "effective_to": price.get("effective_to") or "Open-ended",
                    "status": price.get("status") or "N/A",
                    "promotion_id": price.get("promotion_id") or "N/A",
                }
            )

        return context

    @staticmethod
    def get_scope_label(scope):
        if scope == "COUNTRY":
            return "Country price"

        if scope == "STORE":
            return "Store price"

        return "Unknown scope"

    @staticmethod
    def format_amount(amount, currency_code):
        if amount is None:
            return "N/A"

        if currency_code:
            return f"{amount} {currency_code}"

        return str(amount)


class PromotionsView(TemplateView):
    template_name = "core/promotions.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["api_error"] = None
        context["promotions"] = []

        try:
            promotions = api_get("/promotions")
        except ApiClientError as exc:
            context["api_error"] = str(exc)
            return context

        product_lookup = build_product_lookup()

        for promotion in promotions:
            product_display = get_product_display(
                promotion.get("product_id"),
                product_lookup,
            )

            context["promotions"].append(
                {
                    "code": promotion.get("code") or "N/A",
                    "name": promotion.get("name") or "N/A",
                    "description": promotion.get("description") or "N/A",
                    "discount_type": promotion.get("discount_type") or "N/A",
                    "discount_value": self.format_discount_value(
                        promotion.get("discount_type"),
                        promotion.get("discount_value"),
                    ),
                    "product_id": promotion.get("product_id") or "N/A",
                    "product_code": product_display["product_code"],
                    "product_name": product_display["product_name"],
                    "image_url": product_display["image_url"],
                    "image_alt": product_display["image_alt"],
                    "scope": self.get_scope(promotion.get("store_id")),
                    "country_id": promotion.get("country_id") or "N/A",
                    "store_id": promotion.get("store_id") or "N/A",
                    "start_date": promotion.get("start_date") or "N/A",
                    "end_date": promotion.get("end_date") or "N/A",
                    "status": "Active" if promotion.get("active") is True else "Inactive",
                }
            )

        return context

    @staticmethod
    def get_scope(store_id):
        if store_id is None:
            return "Country promotion"

        return "Store promotion"

    @staticmethod
    def format_discount_value(discount_type, discount_value):
        if discount_value is None:
            return "N/A"

        if discount_type == "PERCENTAGE":
            return f"{discount_value}%"

        return str(discount_value)


class PriceChangeRequestsView(TemplateView):
    template_name = "core/price_change_requests.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["api_error"] = None
        context["price_change_requests"] = []

        try:
            requests = api_get("/price-change-requests")
        except ApiClientError as exc:
            context["api_error"] = str(exc)
            return context

        product_lookup = build_product_lookup()

        for request in requests:
            product_display = get_product_display(
                request.get("product_id"),
                product_lookup,
            )

            context["price_change_requests"].append(
                {
                    "id": request.get("id") or "N/A",
                    "product_id": request.get("product_id") or "N/A",
                    "product_code": product_display["product_code"],
                    "product_name": product_display["product_name"],
                    "image_url": product_display["image_url"],
                    "image_alt": product_display["image_alt"],
                    "scope": self.get_scope(request.get("store_id")),
                    "country_id": request.get("country_id") or "N/A",
                    "store_id": request.get("store_id") or "N/A",
                    "old_price_amount": request.get("old_price_amount") or "N/A",
                    "requested_price_amount": request.get("requested_price_amount") or "N/A",
                    "status": request.get("status") or "N/A",
                    "justification": request.get("justification") or "N/A",
                    "requested_effective_date": request.get("requested_effective_date") or "N/A",
                    "rejection_reason": request.get("rejection_reason") or "N/A",
                    "created_at": request.get("created_at") or "N/A",
                }
            )

        return context

    def post(self, request, *args, **kwargs):
        action = request.POST.get("action")
        price_change_request_id = request.POST.get("request_id")

        if not price_change_request_id:
            messages.error(request, "Missing pricing request identifier.")
            return redirect("core:price_change_requests")

        if action == "approve":
            return self.approve_request(price_change_request_id)

        if action == "reject":
            return self.reject_request(request, price_change_request_id)

        messages.error(request, "Unknown workflow action.")
        return redirect("core:price_change_requests")

    def approve_request(self, price_change_request_id):
        payload = {
            "approved_by_user_id": 1,
        }

        try:
            api_post(
                f"/price-change-requests/{price_change_request_id}/approve",
                payload=payload,
            )
        except ApiClientError as exc:
            messages.error(
                self.request,
                f"Pricing request could not be approved: {exc}",
            )
            return redirect("core:price_change_requests")

        messages.success(
            self.request,
            f"Pricing request #{price_change_request_id} approved successfully.",
        )
        return redirect("core:price_change_requests")

    def reject_request(self, request, price_change_request_id):
        reason = request.POST.get("reason", "").strip()

        if not reason:
            messages.error(request, "A rejection reason is required.")
            return redirect("core:price_change_requests")

        payload = {
            "rejected_by_user_id": 1,
            "reason": reason,
        }

        try:
            api_post(
                f"/price-change-requests/{price_change_request_id}/reject",
                payload=payload,
            )
        except ApiClientError as exc:
            messages.error(
                request,
                f"Pricing request could not be rejected: {exc}",
            )
            return redirect("core:price_change_requests")

        messages.success(
            request,
            f"Pricing request #{price_change_request_id} rejected successfully.",
        )
        return redirect("core:price_change_requests")

    @staticmethod
    def get_scope(store_id):
        if store_id is None:
            return "Country request"

        return "Store request"


class PriceChangeRequestCreateView(TemplateView):
    template_name = "core/price_change_request_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = kwargs.get("form") or PriceChangeRequestForm()
        context["api_error"] = None
        return context

    def post(self, request, *args, **kwargs):
        form = PriceChangeRequestForm(request.POST)

        if not form.is_valid():
            return self.render_to_response(self.get_context_data(form=form))

        try:
            api_post("/price-change-requests", payload=form.to_api_payload())
        except ApiClientError as exc:
            return self.render_to_response(
                self.get_context_data(
                    form=form,
                    api_error=str(exc),
                )
            )

        messages.success(request, "Pricing request created successfully.")
        return redirect("core:price_change_requests")


class PriceHistoryView(TemplateView):
    template_name = "core/price_history.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["api_error"] = None
        context["price_history"] = []

        try:
            history_items = api_get("/price-history")
        except ApiClientError as exc:
            context["api_error"] = str(exc)
            return context

        product_lookup = build_product_lookup()

        for item in history_items:
            product_display = get_product_display(
                item.get("product_id"),
                product_lookup,
            )

            context["price_history"].append(
                {
                    "history_id": item.get("history_id") or "N/A",
                    "price_change_request_id": item.get("price_change_request_id") or "N/A",
                    "product_id": item.get("product_id") or "N/A",
                    "product_code": product_display["product_code"],
                    "product_name": product_display["product_name"],
                    "image_url": product_display["image_url"],
                    "image_alt": product_display["image_alt"],
                    "scope": self.get_scope(item.get("store_id")),
                    "country_id": item.get("country_id") or "N/A",
                    "store_id": item.get("store_id") or "N/A",
                    "previous_price_id": item.get("previous_price_id") or "N/A",
                    "new_price_id": item.get("new_price_id") or "N/A",
                    "old_price_amount": item.get("old_price_amount") or "N/A",
                    "new_price_amount": item.get("new_price_amount") or "N/A",
                    "applied_by_user_id": item.get("applied_by_user_id") or "N/A",
                    "applied_at": item.get("applied_at") or "N/A",
                    "created_at": item.get("created_at") or "N/A",
                    "reason": f"Applied from request #{item.get('price_change_request_id')}",
                }
            )

        return context

    @staticmethod
    def get_scope(store_id):
        if store_id is None:
            return "Country price change"

        return "Store price change"


class AnomaliesView(TemplateView):
    template_name = "core/anomalies.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["api_error"] = None
        context["anomalies"] = []

        try:
            anomalies = api_get("/anomalies")
        except ApiClientError as exc:
            context["api_error"] = str(exc)
            return context

        product_lookup = build_product_lookup()

        for anomaly in anomalies:
            product_display = get_product_display(
                anomaly.get("product_id"),
                product_lookup,
            )

            context["anomalies"].append(
                {
                    "anomaly_type": anomaly.get("anomaly_type") or "N/A",
                    "severity": anomaly.get("severity") or "N/A",
                    "message": anomaly.get("message") or "N/A",
                    "description": anomaly.get("message") or "N/A",
                    "promotion_id": anomaly.get("promotion_id") or "N/A",
                    "product_id": anomaly.get("product_id") or "N/A",
                    "product_code": product_display["product_code"],
                    "product_name": product_display["product_name"],
                    "image_url": product_display["image_url"],
                    "image_alt": product_display["image_alt"],
                    "store_id": anomaly.get("store_id") or "N/A",
                    "sales_count": anomaly.get("sales_count") or 0,
                    "total_quantity": anomaly.get("total_quantity") or 0,
                    "total_revenue": anomaly.get("total_revenue") or "N/A",
                    "threshold": anomaly.get("threshold") or "N/A",
                    "is_resolved": False,
                    "detected_at": "N/A",
                }
            )

        return context