from decimal import Decimal, InvalidOperation

from django.views.generic import TemplateView

from services.api_client import ApiClientError, api_get, api_post
from django.contrib import messages
from django.shortcuts import redirect
from core.forms import PriceChangeRequestForm

class HomeView(TemplateView):
    template_name = "core/home.html"


class DashboardView(TemplateView):
    template_name = "core/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["api_error"] = None
        context["kpi_cards"] = []

        try:
            kpis = api_get("/kpis")
        except ApiClientError as exc:
            context["api_error"] = str(exc)
            return context

        context["kpi_cards"] = [
            {
                "label": "Total sales",
                "value": self.format_number(kpis.get("total_sales_count")),
                "description": "Number of sales transactions.",
            },
            {
                "label": "Total quantity sold",
                "value": self.format_number(kpis.get("total_quantity")),
                "description": "Total units sold across all transactions.",
            },
            {
                "label": "Total revenue",
                "value": self.format_number(kpis.get("total_revenue")),
                "description": "Revenue generated by all sales.",
            },
            {
                "label": "Promo sales",
                "value": self.format_number(kpis.get("promo_sales_count")),
                "description": "Sales transactions linked to a promotion.",
            },
            {
                "label": "Promo revenue",
                "value": self.format_number(kpis.get("promo_revenue")),
                "description": "Revenue generated by promotional sales.",
            },
            {
                "label": "Promo sales share",
                "value": self.format_percentage(kpis.get("promo_sales_share")),
                "description": "Share of sales transactions linked to promotions.",
            },
            {
                "label": "Average order value",
                "value": self.format_number(kpis.get("average_order_value")),
                "description": "Average revenue per sales transaction.",
            },
        ]

        return context

    @staticmethod
    def format_number(value):
        if value is None:
            return "N/A"

        try:
            return f"{Decimal(str(value)):,.2f}"
        except (InvalidOperation, ValueError):
            return str(value)

    @staticmethod
    def format_percentage(value):
        if value is None:
            return "N/A"

        try:
            return f"{Decimal(str(value)) * Decimal('100'):.2f}%"
        except (InvalidOperation, ValueError):
            return str(value)



class ProductsView(TemplateView):
    template_name = "core/products.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["api_error"] = None
        context["products"] = []

        try:
            products = api_get("/products")
        except ApiClientError as exc:
            context["api_error"] = str(exc)
            return context

        context["products"] = [
            {
                "code": product.get("code") or "N/A",
                "name": product.get("name") or "N/A",
                "brand": product.get("brand") or "N/A",
                "model": product.get("model") or "N/A",
                "family_name": self.get_family_name(product),
                "description": product.get("description") or "N/A",
                "status": "Active" if product.get("active") is True else "Inactive",
            }
            for product in products
        ]

        return context

    @staticmethod
    def get_family_name(product):
        family = product.get("family")

        if not family:
            return "N/A"

        return family.get("name") or "N/A"


class PricesView(TemplateView):
    template_name = "core/prices.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["api_error"] = None
        context["prices"] = []

        try:
            prices = api_get("/prices")
        except ApiClientError as exc:
            context["api_error"] = str(exc)
            return context

        context["prices"] = [
            {
                "product_code": price.get("product_code") or "N/A",
                "product_name": price.get("product_name") or "N/A",
                "scope": price.get("price_scope") or "N/A",
                "scope_label": self.get_scope_label(price.get("price_scope")),
                "type": price.get("price_type") or "N/A",
                "amount": self.format_amount(
                    price.get("amount"),
                    price.get("currency_code"),
                ),
                "country_id": price.get("country_id") or "N/A",
                "store_id": price.get("store_id") or "N/A",
                "effective_from": price.get("effective_from") or "N/A",
                "effective_to": price.get("effective_to") or "Open-ended",
                "status": price.get("status") or "N/A",
                "promotion_id": price.get("promotion_id") or "N/A",
            }
            for price in prices
        ]

        return context

    @staticmethod
    def get_scope_label(scope):
        if scope == "COUNTRY":
            return "Country price"

        if scope == "STORE":
            return "Store price"

        return "Unknown scope"

    @staticmethod
    def format_amount(amount, currency_code):
        if amount is None:
            return "N/A"

        if currency_code:
            return f"{amount} {currency_code}"

        return str(amount)


class PromotionsView(TemplateView):
    template_name = "core/promotions.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["api_error"] = None
        context["promotions"] = []

        try:
            promotions = api_get("/promotions")
        except ApiClientError as exc:
            context["api_error"] = str(exc)
            return context

        context["promotions"] = [
            {
                "code": promotion.get("code") or "N/A",
                "name": promotion.get("name") or "N/A",
                "description": promotion.get("description") or "N/A",
                "discount_type": promotion.get("discount_type") or "N/A",
                "discount_value": self.format_discount_value(
                    promotion.get("discount_type"),
                    promotion.get("discount_value"),
                ),
                "product_id": promotion.get("product_id") or "N/A",
                "scope": self.get_scope(promotion.get("store_id")),
                "country_id": promotion.get("country_id") or "N/A",
                "store_id": promotion.get("store_id") or "N/A",
                "start_date": promotion.get("start_date") or "N/A",
                "end_date": promotion.get("end_date") or "N/A",
                "status": "Active" if promotion.get("active") is True else "Inactive",
            }
            for promotion in promotions
        ]

        return context

    @staticmethod
    def get_scope(store_id):
        if store_id is None:
            return "Country promotion"

        return "Store promotion"

    @staticmethod
    def format_discount_value(discount_type, discount_value):
        if discount_value is None:
            return "N/A"

        if discount_type == "PERCENTAGE":
            return f"{discount_value}%"

        return str(discount_value)


class PriceChangeRequestsView(TemplateView):
    template_name = "core/price_change_requests.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["api_error"] = None
        context["price_change_requests"] = []

        try:
            requests = api_get("/price-change-requests")
        except ApiClientError as exc:
            context["api_error"] = str(exc)
            return context

        context["price_change_requests"] = [
            {
                "id": request.get("id") or "N/A",
                "product_id": request.get("product_id") or "N/A",
                "scope": self.get_scope(request.get("store_id")),
                "country_id": request.get("country_id") or "N/A",
                "store_id": request.get("store_id") or "N/A",
                "old_price_amount": request.get("old_price_amount") or "N/A",
                "requested_price_amount": request.get("requested_price_amount") or "N/A",
                "status": request.get("status") or "N/A",
                "justification": request.get("justification") or "N/A",
                "requested_effective_date": request.get("requested_effective_date") or "N/A",
                "rejection_reason": request.get("rejection_reason") or "N/A",
                "created_at": request.get("created_at") or "N/A",
            }
            for request in requests
        ]

        return context

    @staticmethod
    def get_scope(store_id):
        if store_id is None:
            return "Country request"

        return "Store request"

class PriceChangeRequestCreateView(TemplateView):
    template_name = "core/price_change_request_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = kwargs.get("form") or PriceChangeRequestForm()
        context["api_error"] = kwargs.get("api_error")
        return context

    def post(self, request, *args, **kwargs):
        form = PriceChangeRequestForm(request.POST)

        if not form.is_valid():
            return self.render_to_response(self.get_context_data(form=form))

        try:
            api_post("/price-change-requests", payload=form.to_api_payload())
        except ApiClientError as exc:
            return self.render_to_response(
                self.get_context_data(
                    form=form,
                    api_error=str(exc),
                )
            )

        messages.success(request, "Pricing request created successfully.")
        return redirect("core:price_change_requests")