name: Backend CI

on:
  push:
  pull_request:

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: pip install uv

      - name: Show Python version
        run: python --version

      - name: Check backend folder exists
        run: test -d backend

      - name: Install backend dependencies
        working-directory: backend
        run: uv sync